name: base_model_getx
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

#version: 版本名称（例如：1.0.0）+版本编号（例如：1）
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #状态管理
  get: ^4.6.1
  #网络请求
  dio: ^4.0.6
  connectivity_plus: ^2.2.1
  pretty_dio_logger: ^1.1.1
  #屏幕适配
  flutter_screenutil: ^5.3.1
  #缓存
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  #弹窗dialog 加载loding
  flutter_smart_dialog: ^3.4.1
  #下拉刷新
  pull_to_refresh: ^2.0.0
  #列表分帧优化（性能优化组件）
  keframe: ^2.0.4
  #包信息
  package_info: ^2.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
